# -*- coding: utf-8 -*-
"""
Created on Thu Jul  4 16:36:06 2024

@author: ncortor
"""

import os
import shutil
import time
import subprocess
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta
import csv
import psutil
import platform


__author__ = 'Ing. MSc.  PhD(c) Nicolás Cortés-Torres'
__copyright__ = "Copyright 2024, DDL"
__credits__ = ["Nicolás Cortés-Torres"]
__license__ = "GIMHA"
__version__ = "0.1"
__maintainer__ = "Nicolás Cortés-Torres"
__email__ = 'ncortor@doctor.upv.es, ingcortest@gmail.com'
__status__ = "developing"

#%%######## FUNCTIONS ################################################################################

################################################################################
# Function to replace scale data
def replace_scale(vec):
    if "1k" in vec:
        vec = "1000"
    elif "2p5" in vec:
        vec = "2500"
    elif "5k" in vec:
        vec = "5000"
    elif "30m" in vec:
        vec = "30"
    elif "200m" in vec:
        vec = "200"
    elif "500m" in vec:
        vec = "500"
    return vec

################################################################################
# Function to set the current time
def def_hora():
    return time.strftime("%d-%m-%Y %H:%M:%S", time.localtime())

################################################################################
def leer_ultima_frecuencia(hwinfo_log_path, freq_col_name):
    """
    Read the latest available frequency from the HWiNFO in monitor.csv file.
    """
    try:
        with open(hwinfo_log_path, 'r', encoding='utf-8', errors='ignore') as f:
            reader = csv.DictReader(f)
            last_row = None
            for row in reader:
                if row[freq_col_name]:
                    last_row = row
        if last_row:
            valor = last_row[freq_col_name].replace(",", ".").strip()
            return float(valor)
    except Exception:
        return None 
    
################################################################################
# Function to run an .exe and measure the time
def run_exe_monitor(exe_name, path_model, hwinfo_log_path, freq_col_name):
    """
    Run an executable and measure the execution time, as well as the average processor frequency.

    Parameters:
    - exe_name: name of the executable file (e.g., “Toparc.exe”)
    - path_model: path to the directory where the executable is located
    - hwinfo_log_path: full path to the .csv file generated by HWiNFO
    - freq_col_name: exact name of the column containing the frequency in MHz

    Returns:
    - Dictionary with times and average frequency
    """
    print("Starting monitoring and execution of the process...")
    try:
        freq_values = []
    
        os.chdir(path_model)
        process = subprocess.Popen([exe_name])
    
        start_time = time.time()
    
        while process.poll() is None:
            freq_now = leer_ultima_frecuencia(hwinfo_log_path, freq_col_name)
            if freq_now:
                freq_values.append(freq_now)
                print(f"{time.strftime('%H:%M:%S')} - Frequency: {freq_now:.2f} MHz")
            time.sleep(1)
    
        end_time = time.time()
    
        exec_time = end_time - start_time #Calcula el tiempo total de ejecución
        freq_promedio = (sum(freq_values) / len(freq_values))/1000 if freq_values else float('nan') #Calcula el promedio de velocidad del procesador
    
        days = exec_time // 86400
        hours = (exec_time % 86400) // 3600
        minutes = (exec_time % 3600) // 60
        seconds = round(exec_time % 60, 1)
        total_days = exec_time / 86400
        total_hours = exec_time / 3600
        total_minutes = exec_time / 60
        
        return exec_time, days, hours, minutes, seconds, total_days, total_hours, total_minutes, freq_promedio
    
    except Exception as e:
        
        print(f"Error while executing the process: {e}")
        # Retornar un conjunto de valores indicativos
        return tuple(["NOT EXECUTABLE"] * 9)
    
################################################################################
# Function to extract information from the computer

def info_pc(info_equipo, carac):
    # Search the entire DataFrame to see if it contains the text “Processor name:
    mask = info_equipo.apply(lambda row: row.astype(str).str.contains(carac)).any(axis=1)

    # Obtain the indexes (positions) where it was found
    indices = info_equipo[mask].index.tolist()

    variable = info_equipo.iloc[indices[0], 1]
    
    return variable


#%%###############################################################################################################
##### Code to meseure Topolco.sds han Hantec.sds generation times ###############################################################
##################################################################################################################
tic = time.time()   # Start timer for script execution tracking
print(f"Start code - {def_hora()}")

# --- Working paths, modify if necessary ---
name_pc = "GIMHABOG"                                        # Please enter the name of the computer that needs to be analysed (Modify if necessary)
wd_path = "D:/Mod_rendimientos/Modelos/"                    # Location of the models to be analyzed (Modify if necessary)
wd_tetis = "C:/Tetis9/bin/"                                 # Directory of TETIS .exe files (Do not modify the root of the TETIS bin files)
wd_out = "D:/Mod_rendimientos/Res/"                         # Location of code results (Modify if necessary)
Res_all = f"{wd_out}Results_toparc_hantec_{name_pc}.csv"    # CSV file to save the results (Modify if necessary)

# --- Control files paths and Column Names ---
monitor_file = "D:/Mod_rendimientos/Monitor/monitoreo.csv" # Define the file path for the system performance monitor data (Modify if necessary)
equipo_file = "D:/Mod_rendimientos/Monitor/equipo.csv"     # Define the file path for the hardware/equipment configuration data (Modify if necessary)
col_monitor = "Relojes núcleo (avg) [MHz]"                 # Define the exact column name for the average core clock speed in the monitor file (Modify if necessary)

# --- Output Directory Management ---
# Check if the output directory (wd_out) exists. If not, create it.
if not os.path.exists(wd_out): 
    os.makedirs(wd_out)         # Create the directory (including any necessary parent directories)
    
   
# --- Model Directory Discovery ---
# Get a list of all subdirectories (which are assumed to be individual models)
# located within the main working directory (wd_path).
# The 'wd_out' folder is implicitly excluded if it's the output folder being checked above, 
# although a robust check might explicitly exclude it if it's named in 'wd_path'.
models = [nombre for nombre in os.listdir(wd_path)
              if os.path.isdir(os.path.join(wd_path, nombre))]

n_models = len(models)

# --- Results Initialization ---
# Initialize an empty list to store the results processed from all models
results = []

print(f"Start Model Analysis - {def_hora()}")

#%% Loop for models
# Iterate through each discovered model directory
for i in range(len(models)):
    
    wd_model = f"{wd_path}{models[i]}/"  # Define the model working directory path

    print(f"   Processing model: {i+1} de {n_models} - {def_hora()}")
    # Extract model metadata from the directory name
    parts = models[i].split('_')
    cuenca = parts[1].upper()                       # Basin name
    escala = replace_scale(parts[2])                # Scale information
    escenario = parts[3].upper()                    # Scenario name
    modelo = f"{parts[1]}_{parts[2]}_{parts[3]}"    # Full model identifier

    #%% Modify the FileSSP.tet configuration file
    wd_FileSSP = f"{wd_model}FileSSP.tet"
    with open(wd_FileSSP, "r") as file:
        changeFileSSP = file.readlines()  # Path to the configuration file
    
    changeFileSSP[0] = wd_model + "\n"  # Modify the first line to set the correct model working directory path
    
    # Write the modified lines to a FileSSP.txt (optional step, often for debugging/legacy)
    with open(f"{wd_model}FileSSP.txt", "w") as file:
        file.writelines(changeFileSSP)
    
    # Overwrite FileSSP.tet with the necessary runtime modifications
    with open(wd_FileSSP, "w") as file:
        file.writelines(changeFileSSP)
    
    #%% Copy executable files (.exe) to the model directory
    for exe_file in ["Toparc.exe", "Hantec.exe", "Control.exe", "Tetis.exe"]:
        shutil.copy(os.path.join(wd_tetis, exe_file), wd_model)
        
    #%% --- Measure Execution Time for Toparc.exe --- 
    print(f"       Executing Topolco: {models[i]} - {def_hora()}")
    
    Res_toparc = run_exe_monitor("Toparc.exe", wd_model, monitor_file, col_monitor) # Execute Toparc.exe
    
    # Split each line in the list into columns based on spaces
    wd_topolco = f"{wd_model}Topolco.sds"
    with open(wd_topolco, "r") as file:
        topolco = file.readlines() 
    
    # Extract the number of cells (basin cell count).
    topolco = [line.split() for line in topolco]
    celdas = int(topolco[6][1])
    
    # --- Check File Existence and Calculate Size Metrics ---
    
    # Check if the Topolco.sds file exists
    if os.path.isfile(wd_topolco):
        topolco_tamaño_bytes  = os.path.getsize(wd_topolco)     # Get the size of the file in bytes
        topolco_tamaño_kb = topolco_tamaño_bytes / 1024         # Convert size from bytes to kilobytes (KB)
        topolco_tamaño_mb = topolco_tamaño_kb / 1024            # Convert size from kilobytes (KB) to megabytes (MB)
        topolco_tamaño_gb = topolco_tamaño_mb / 1024            # Convert size from megabytes (MB) to gigabytes (GB)
    
    #%% --- Measure Execution Time for Hantec.exe ---
    print(f"       Executing Hantec: {models[i]} - {def_hora()}")
    
    Res_hantec = run_exe_monitor("Hantec.exe", wd_model, monitor_file, col_monitor) # Execute Hantec.exe
  
    # Define the path to the generated Hantec.sds file
    wd_hantec = f"{wd_model}Hantec.sds" 

    # --- Calculate Hantec File Size Metrics ---
    # Check if the Hantec.sds file was created successfully
    if os.path.isfile(wd_hantec):
        hantec_tamaño_bytes  = os.path.getsize(wd_hantec)   # Get the size of the file in bytes
        hantec_tamaño_kb = hantec_tamaño_bytes / 1024       # Convert size from bytes to kilobytes (KB)
        hantec_tamaño_mb = hantec_tamaño_kb / 1024          # Convert size from kilobytes (KB) to megabytes (MB)
        hantec_tamaño_gb = hantec_tamaño_mb / 1024          # Convert size from megabytes (MB) to gigabytes (GB)
    
    #%% --- Aggregate and Store Results for Pre-processing Steps ---
    results.append([
        name_pc, cuenca, escala, escenario, modelo, celdas,
        *Res_toparc, *Res_hantec,
        topolco_tamaño_mb, topolco_tamaño_gb,
        hantec_tamaño_mb, hantec_tamaño_gb,
    ])
    
    # Log the completion of processing for the current model instance
    print(f"   Procesando modelo: {i+1} de {n_models} - {def_hora()}")
        
#%% Create a Pandas DataFrame with the aggregated results 
print(f"Creating Dataframe - {def_hora()}")

df = pd.DataFrame(results, columns=[
    'Equipo', 'Cuenca', 'Escala','Escenario', 'Modelo', 'Celdas',
    'Toparc Time', 'Toparc Days', 'Toparc Hours', 'Toparc Minutes', 'Toparc Seconds',
    'Toparc Total Days', 'Toparc Total Hours', 'Toparc Total Minutes', 'Vel_Toparc',
    'Hantec Time', 'Hantec Days', 'Hantec Hours', 'Hantec Minutes', 'Hantec Seconds',
    'Hantec Total Days', 'Hantec Total Hours', 'Hantec Total Minutes','Vel_Hantec',
    'Tamaño Topolco mb', 'Tamaño Topolco gb',
    'Tamaño Hantec mb', 'Tamaño Hantec gb'
])


#%% --- Extracting Hardware Information (Equipo Info) ---
print(f"Adding extra columns - {def_hora()}")

# Read the hardware info file as plain text using robust "utf-8" encoding
with open(equipo_file, encoding="utf-8") as f:
    info_equipo = f.readlines() # Read all lines into a list
    
# Process the list of lines into a structured DataFrame      
info_equipo = pd.DataFrame(info_equipo) # Convert list of lines into a DataFrame (single column)
# Remove leading/trailing whitespace, then split the column by commas (assuming CSV format)
info_equipo = info_equipo[0].str.strip().str.split(",", expand=True)

# Extract specific hardware details using a custom function 'info_pc'
# (Assuming info_pc searches the DataFrame based on a descriptive string)
procesador = info_pc(info_equipo, "Nombre del procesador:")                     # Processor Name (CPU Model)
memoria_ram_gb = info_pc(info_equipo, "Tamaño de memoria total:")               # Total RAM Size
nucleos = info_pc(info_equipo, "Número de núcleos de procesador:")              # Number of Physical Cores
procesadores_logicos = info_pc(info_equipo, "Número de procesadores lógicos:")  # Number of Logical Processors (Threads)

# Create repeated columns with the same hardware information for all rows in the DataFrame (df)
df['Procesador'] = procesador                       # Add Processor Name column
df['Memoria Ram Gb'] = memoria_ram_gb               # Add Total RAM Size column
df['Nucleos'] = nucleos                             # Add Number of Physical Cores column
df['Procesadores logicos'] = procesadores_logicos   # Add Number of Logical Processors column

#%% --- Save the DataFrame to a CSV file ---
print(f"Saving results - {def_hora()}")

# Write the final aggregated DataFrame (df) to a CSV file (Res_all).
df.to_csv(Res_all, index=False)
print(f"Fin ejecución - {def_hora()}")

##########################################################################################################################
#################                               END CODE                         #########################################
##########################################################################################################################

run_time = (time.time() - tic)
hours_ = run_time // 3600.0
minutes_ = round((run_time / 3600.0 - hours_) * 60.0, 1)
text_ = f'Execution total time was {hours_} hours and {minutes_} minutes'
len_text = len(text_)
len_print = len_text + 2 * 10
len_blank = (len_print - 2)
print(len_print * '#')
print('#' + len_blank * ' ' + '#')
print('#' + 9 * ' ' + text_ + 9 * ' ' + '#')
print('#' + len_blank * ' ' + '#')
print(len_print * '#')


